### ISSUE TITLE
Perte de connexion

### ISSUE THREAD

**Issue by Lachnicaille** [Trackerz/Yggtorrent-DLM#1]
Hey Trackerz

J'ai essayé ce .DLM avec mon syno DS218+ et j'observe qu'une fois le dlm ajouté à la liste des modules de recherche BT je réussis bien à passer le test de connexion avec mon compte YGG. En revanche, je lance ensuite une recherche de torrent et je n'ai jamais de résultat. Que pasa ? Je retourne donc sur la page de configuration Recherche BT de DLS. Je teste à nouveau la connexion du dlm et j'obtiens cette fois un message d'erreur (compte mot de passe non valable). La connexion ne se fait donc plus..... Si je supprime le module, que je le re-crée, je teste immédiatement la connexion : elle est OK... Mais après çà déraille à nouveau. En fait le test de connexion ne fonctionne qu'une fois : quand on clique sur Vérifier juste après avoir ajouté le module à la liste. 

Je reste disponible pour toute info info qui apporterait de l'eau à ce moulin.

Merci de ton aide !

**Comment by Lachnicaille** [comment]
UP !

**Comment by Trackerz** [comment]
Yo, tu es sous VPN sur ton NAS ou pas? Si t'es sous VPN le problème vient certainement de la et on ne va rien pouvoir y faire mais si ce n'est pas le cas tu peux essayer de faire ces manips

Il faudrait te connecter en ssh avec un compte utilisateur qui a les droits admin sur le NAS pour supprimer les cookies et taper les commandes suivantes

1 - une fois connecté en ssh taper sudo -i puis taper le mot de passe de ton compte
2 - cd /tmp
3 - rm *.cookie*
4 - Refaire un tentative

Il faut aussi bien vérifier que t'as php 7.2 minimum et les extensions php CURL et BCMATH bien actives

Si ca ne marche pas ajoute moi sur discord pour regarder ce qu'il se passe Trackerz#1588

**Comment by Trackerz** [comment]
Effectivement suite à des changements (encore...) coté Cloudflare ca ne fonctionne de nouveau plus mais ce n'est pas un problème car apparemment Cloudflare n'est plus présent sur YGG.

Peux tu refaire un essai avec l'ancienne version qui est présente ici https://github.com/Trackerz/Yggtorrent-DLM/archive/1.2.zip

Pour être certain que tout soit propres avant de faire l'installation tu peux te connecter en SSH sur ton NAS avec un compte qui est administrateur et taper les commandes suivantes pour supprimer les anciens cookies

1 : ssh ip -p port -l identifiant (exemple ssh 192.168.0.1 -p 22 -l admin)
2 : sudo -i puis taper le mot de passe du compte utilisateur une nouvelle fois
3 : cd /tmp
1 : rm *.cookie\*

Pour l'utiliser il faut simplement copier le fichier **ygg.php** à la racine du dossier web et avoir l'extension php **CURL** active (plus besoin de BCMATH) puis ajouter à DownloadStation le module **yggtorrent.dlm** présent dans la version 1.2 (bien supprimer le 2.0 avant et non l'écraser)

Chez moi l'ancienne version fonctionne sous problème mais si tu as un soucis tu peux m'ajouter sur Discord voir ce qu'il se passe **Trackerz#1588**

**Comment by Lachnicaille** [comment]
Nickel !
Merci beaucoup Trackerz. Cela fonctionne désormais ! Je te confirme que la suppression du cookie était indispensable. Take care !
