### ISSUE TITLE
Interface avec Alldebrid

### ISSUE THREAD

**Issue by athenard** [Trackerz/Yggtorrent-DLM#11]
Salut ! 
Tout d'abord merci pour ton projet, ça marche déjà super bien.
Je me demande s'il était possible d'interfacer ça directement avec Alldebrid ? 
De pouvoir directement "convertir" le torrent en DDL en faisant la recherche depuis Download Station ? 

Merci bcp !

**Comment by Trackerz** [comment]
Salut ! Désolé c'est uniquement fait pour fonctionner avec WebStation et il n'est pas prévu de le rendre compatible avec autre chose :(
