### ISSUE TITLE
Le faire tourner sur Docker

### ISSUE THREAD

**Issue by Risengan** [Trackerz/Yggtorrent-DLM#12]
Merci beaucoup, ça fonctionne super bien !
Savez-vous s'il est possible de le faire tourner dans Docker plutôt que sur WebStation ? Merci !

**Comment by Trackerz** [comment]
Salut ! Désolé c'est uniquement fait pour fonctionner avec WebStation et il n'est pas prévu de le rendre compatible avec autre chose :(
