### ISSUE TITLE
Recherche HS

### ISSUE THREAD

**Issue by wawa75018** [Trackerz/Yggtorrent-DLM#13]
Bonjour,

La recherche depuis Download Station ne fonctionne plus. Quand  je vérifie mon login et mot de passe dans les paramètres de Download Station. Il indique que mon compte est invalide alors que ça fonctionne bien sur ygg torrent 

Merci ;-)

**Comment by Trackerz** [comment]
Salut, effectivement le site Mastodont ou je récup l'adresse du site dynamique a changé il est passe sur du React ce qui change toute la structure du coup ca casse le script. J'ai déjà trouvé une solution qui devrait régler ca, je vais m'en occuper ce weekend :)

**Comment by wawa75018** [comment]
Top ! Merci ;-)

**Comment by Trackerz** [comment]
C'est mis à jour si tu peux me dire si c'est ok

**Comment by wawa75018** [comment]
Merci beaucoup, c'est ok sur DSM 7.0
