### ISSUE TITLE
Message d'erreur "Le compte ou le mot de passe n'est pas valable"

### ISSUE THREAD

**Issue by Pitopocco** [Trackerz/Yggtorrent-DLM#14]
Bonjour,

Je n'ai plus le "connexion réussie" sur download station mais "Le compte ou le mot de passe n'est pas valable".
J'ai vérifié toute la conf et ai supprimé et ajouté de nouveau le dlm.

Merci par avance :D

**Comment by Trackerz** [comment]
Salut, effectivement le site Mastodont ou je récup l'adresse du site dynamique a changé il est passe sur du React ce qui change toute la structure du coup ca casse le script. J'ai déjà trouvé une solution qui devrait régler ca, je vais m'en occuper ce weekend :)

**Comment by Pitopocco** [comment]
Ah génial merci beaucoup ! :D

**Comment by Trackerz** [comment]
C'est mis à jour si tu peux me dire si c'est ok

**Comment by Pitopocco** [comment]
Ça ne fonctionne toujours pas...
J'ai supprimé le dlm et remit mais j'ai toujours le message d'erreur disant que le mot de passe ou le user est incorrect alors que sur ygg ça fonctionne. Sais tu quelle manip je pourrais faire stp ? Merci beaucoup par avance

**Comment by Trackerz** [comment]
Essaye de supprimer le dlm puis download station et de tout réinstaller j'ai eu le soucis aussi

**Comment by Pitopocco** [comment]
C'est bon je viens de désinstaller download station et de tout refaire avec le 1.3.6 et tout refonctionne ! Merci beaucoup à toi ! Et je suis en dsm 7 pour info.
