### ISSUE TITLE
Modifier l'url dans le fichier INFO

### ISSUE THREAD

**Issue by poluket** [Trackerz/Yggtorrent-DLM#16]
L'url du site a changé. 
la fonction recherche ne fonctionne plus.
pouvez vous mettre a jour l'URL

Merci

**Comment by Trackerz** [comment]
De mon coté ca fonctionne

Si tu passes par un VPN ca peut venir de la car ca fait pop Cloudflare 

Sinon t'es sous quelle version de DSM?

**Comment by poluket** [comment]
salut,

merci pour le feedback

je suis bien en 1.3.7 de ton plugin

je ne passe pas par un VPN
je suis sous la version DSM 7.2-64570 Update 1

il me met que le compte ou le mot de passe n'est pas valable dans le syno alors que l'utilisateur et le mot de passe passe bien au niveau du site. cela ressemble beaucoup a l'autre issue ouverte.

**Comment by Trackerz** [comment]
J'ai fait des tests ca semble aussi fonctionner en 7.2 c'est étrange

Si t'as discord ajoute moi > trackerz

**Comment by loicpavard** [comment]
Pour info, je viens d´y passer qques minutes et je confirme que jái aussi reussi a le faire fonctioner sur DSM 7.2-64570.

Une fois l'ajout du plugin et le couple login/password saisi pour verifier authentification, jái du relancer DL Station pour que les resultats du tracker sortent.
SInon, la recherche me renvoyait "No match found".

Merci pour le job.

**Comment by poluket** [comment]
je confirme que c'est bon, ce que j'ai fait chez moi, simplement supprimer le module de recherche de la liste puis le remettre. j'ai même pas modifier le user/pwd et c'est ok

Merci pour le support
