### ISSUE TITLE
Erreur mot de passe non valide

### ISSUE THREAD

**Issue by pierrep26** [Trackerz/Yggtorrent-DLM#18]
Bonjour à tous, j'ai un soucis avec le mot de passe non valide, comment avez vous résolu la situation?

**Comment by Alecent** [comment]
C'est la double authentification de Yggtorrent "privé" qui pose problème, il faudrait refaire le script en prenant en compte cette nouvelle étape, mais je ne suis pas à l'orgine du script et donc pas vraiment vérifié ce qu'il faudrait changer.

**Comment by Trackerz** [comment]
J'ai fait une mise à jour pour supporter la nouvelle version du site -> [1.3.8](https://github.com/Trackerz/Yggtorrent-DLM/releases/tag/1.3.8)

Elle fonctionne uniquement si cloudflare n'est pas actif sur le site et il n'est pas prévu de le bypasser
