### ISSUE TITLE
YggTorrent devient Ygg et le DLM ne fonctionne plus :(

### ISSUE THREAD

**Issue by mbagiella** [Trackerz/Yggtorrent-DLM#19]
Suite au changement de YggTorrent à Ygg rien ne fonctionne plus.
Pourrait-on avoir une maj ?

**Comment by Trackerz** [comment]
J'ai fait une mise à jour pour supporter la nouvelle version du site.
[V 1.3.8](https://github.com/Trackerz/Yggtorrent-DLM/releases/tag/1.3.8)

Elle fonctionne uniquement si cloudflare n'est pas actif sur le site et il n'est pas prévu de le bypasser

**Comment by Trackerz** [comment]
J'ai le meme problème de mon coté mais ca fonctionne quand sans problème, ca doit être bug de download station j'imagine
