### ISSUE TITLE
Aucune donnée dans la Recherche BT

### ISSUE THREAD

**Issue by Skryz974** [Trackerz/Yggtorrent-DLM#2]
Bonjour,

Je viens d'installer le module mais je constate qu'il n'y a aucune donnée.
Je pense que c'est parce que le site à changer entre temps .si au lieu de .se
sur Twitter il n'est pas à jour contrairement à Mastodon c'est peut être ça le problème.

Comment je peux faire?

Merci par avance.

**Comment by Trackerz** [comment]
Je viens de faire un test avec une installation clean ca fonctionne bien de mon coté. tu confirmes que t'as bien activé l'extension php **CURL**? Si oui du coup il faudrait que tu essais de copier le dossier **sources** à la racine de ton dossier **web** sur le NAS puis modifier les lignes 4 et 5 du fichier **test.php** en mettant ton password/login du site comme ceci :

$username = 'tonlogin';
$password = 'tonpass';

Et aussi en ajoutant ceci à la ligne 3 (ca va permettre d'afficher les erreurs si il y en a) :

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

Une fois que c'est bon tu enregistres et tu va sur l'adresse suivante http://ipdetonas/sources/test.php et si t'as une erreur qui s'affiche poste la ici voir ce qu'il se passe.

Autre chose que tu peux essayer c'est de supprimer le cookie en faisant cette manip avec un compte qui est administrateur : 

1 : ssh ip -p port -l identifiant (exemple ssh 192.168.0.1 -p 22 -l admin)
2 : sudo -i puis taper le mot de passe du compte utilisateur une nouvelle fois
3 : cd /tmp
4 : rm *.cookie*

**Comment by Skryz974** [comment]
Merci pour ta réponse.

Oui tout est bien activé j'avais déjà testé également le fichier test.php ça fonctionné bien.
J'ai modifié également le fichier search.php pour prendre en compte le mastodon en premier a la place de twitter. Mais ça n'a rien changé.

Je viens de refaire un test à l'instant depuis l'appli DS Get sur android ça fonctionne... mais pas sur l'interface web.
C'est peut être un problème sur mon PC. Je vais essayé de faire du nettoyage du browsers et supprimer les cookies sur le NAS. Mais comme ça marche sur l'appli de mon smartphone c'est mieux lol.

Merci pour ton aide en tout cas et surtout merci pour le projet ;-)

**Comment by Trackerz** [comment]
Tu n'as pas besoin de faire la modification pour ce qui est de Twitter et Mastodon ne t'en fait pas il prend soit l'un soit l'autre si un des 2 ne fonctionne pas ! 

Du coup la je ne vois pas trop de quoi peut venir le problème, essai de réinstaller DownloadStation qui sait et peut être essayer avec un autre navigateur mais si ca te va l'utilisation depuis l'application tout va bien :)
