### ISSUE TITLE
Impossible de se connecter

### ISSUE THREAD

**Issue by Narror** [Trackerz/Yggtorrent-DLM#22]
Hello, 

Le projet est il toujours fonctionnel ? j'ai tenté de le mettre ne place mais impossible  de se connecter alors que les identifiants sont correct.
![image](https://github.com/user-attachments/assets/13ce598f-9fd9-4145-9400-c093f8b3cd2e)

Je me suis connecté en ssh sur le nas et dans les logs (journalctl) je trouve l'erreur suivante:
```
failed to prepare. reason: ArgumentCountError: Too few arguments to function YGGTorrentDLM::prepare(), 2 passed in /volume1/@appstore/DownloadStation/btsearch/btsearch.php on line 246 and exactly 4 expected in /volume1/@appconf/DownloadStation/download/userplugins/YGG Narror/search.php:202
```

Ce qui semble logique quand on regarde le code de `btsearch.php`.
![image](https://github.com/user-attachments/assets/e61ac56d-9981-4a50-bcbd-ad88cb21e534)

Je ne comprend pas comment le `search.php` peut fonctionner du coup.
![image](https://github.com/user-attachments/assets/8c4a5897-c93c-435c-bf3e-72d5df8041c7)

Je ne sais pas si le `btsearch` a été modifié avec une mise a jour récement :/ et les docs ne sont pas à jour ....

J'ai tenté de modifier le code en retirant `VerifyAccount` dans le prepare du `search.php` en rajoutant le `getDomain` car il n'est pas appelé sinon.
![image](https://github.com/user-attachments/assets/2b1f1dde-52d2-4f2e-90c9-4f18d7aed128)

 Mais c'est sans succès, le code semble finir à la ligne 370 dans le screen ci dessous car le `content` est vide dans la méthode `request`.
![image](https://github.com/user-attachments/assets/953df429-adf5-4e78-bee3-2f5913223ce4)

**Comment by P00nY** [comment]
Hello, 
Cela fonctionne pour ma part. Il te faudra attendre quelque minute après avoir effectué une recherche pour que cela s'affiche connecté. Bug d'affichage sur DS.

**Comment by P00nY** [comment]
Bonjour, 
Normalement si tu suis la procédure et les pré requis dans les versions tout fonctionnera.
Envoies des screens de toute ta conf.

**Comment by naber91** [comment]
Bonjour,
Voilà ma config, je reste toujours en déconnecté même après plusieurs jours, le test via "vérifier fonctionne dans le plugin.
Impossible de faire des recherches.
L'accès au site fonctionne bien, sinon en dehors de ça
![Capture d’écran 2024-11-11 à 12 56 03](https://github.com/user-attachments/assets/44876aea-6fbf-47c4-8284-9014c8a46780)
![Capture d’écran 2024-11-11 à 12 51 36](https://github.com/user-attachments/assets/d6e81507-6534-45e7-a3ef-ea6c9f8177dc)
![Capture d’écran 2024-11-11 à 12 50 45](https://github.com/user-attachments/assets/e80a6353-65a3-4527-a395-546307e1f5af)

**Comment by Trackerz** [comment]
Essaye de faire ceci : 

- Supprimer le plugin de Download Station
- Supprimer Download Station (ne pas oublier de cocher la case pour supprimer tous les paramètres)
- Réinstaller Download Station
/!\ (ne pas installer le plugin pour le moment) /!\
- Tester une recherche via les moteurs par défaut

Si tu as des résultats alors tu peux réinstaller le plugin à partir de maintenant

Coche uniquement "The Pirate bay" et "YGG" comme moteur de recherche et refait une tentative
Si tu as des résultats, tu peux décocher "The Pirate Bay" pour avoir uniquement les résultats d'YGG

**Comment by P00nY** [comment]
Hello,
Autre chose, j'ai contrôlé mes DNS et j'ai laissé celui de ma BOX et donc de mon FAI. 
À tester SANS les DNS de Google 8.8.8.8 ou 8.8.4.4 ou autres DNS.

**Comment by Trackerz** [comment]
En france il vaut mieux laisser les DNS de google (8.8.8.8) ou cloudflare (1.1.1.1) car les FIA bloquent YGG si je ne dis pas de bétises

**Comment by Narror** [comment]
Je cromprend pas comment ça peut marcher chez vous au vu de l'erreur que j'ai mis dans mon post 

failed to prepare. reason: ArgumentCountError: Too few arguments to function YGGTorrentDLM::prepare(), 2 passed in /volume1/@appstore/DownloadStation/btsearch/btsearch.php on line 246 and exactly 4 expected in /volume1/@appconf/DownloadStation/download/userplugins/YGG Narror/search.php:202

**Comment by Trackerz** [comment]
Ajoute moi sur discord trackerz#1588 ou trackerz

**Comment by naber91** [comment]
Je viens de réinstaller uniquement le plugin et ça fonctionne
Merci pour votre aide
Pour info : DNS google pour moi, ça ne fonctionne pas avec ceux de mon FAI

**Comment by P00nY** [comment]
Hello @Trackerz, 
Je pense que tu peux close l'issue ^^
