### ISSUE TITLE
Fichier Torrent non-valide

### ISSUE THREAD

**Issue by LudovicOmarini** [Trackerz/Yggtorrent-DLM#23]
Bonjour,

J'ai exactement la même config' de P00ny https://github.com/Trackerz/Yggtorrent-DLM/issues/21#issuecomment-2395931765 et lorsque que je veux télécharger un torrent, j'ai le message "Fichier Torrent Non-Valide".

Bonne journée

**Comment by P00nY** [comment]
Hello, 
Ta connexion test a fonctionné ? Et peux tu envoyer ta conf et le nom du torrent de yggtorrent.. je vais test de mon côté :) je l'ai aussi sur mon tel

**Comment by LudovicOmarini** [comment]
Salut voici la conf actuelle :

Les paquets installés :
![paquets](https://github.com/user-attachments/assets/ab70cf92-3d80-46e9-bdc4-f3547d20458a)

Contenu du dossier web et droits :
![dossier](https://github.com/user-attachments/assets/b2cd4a13-21b3-409e-ac32-d42bd79b8f3e)
![droits dossier](https://github.com/user-attachments/assets/b5e5aa82-260a-4ca5-afb3-81f255f303f0)

Configuration de WebStation  et PHP :
![conf webstation](https://github.com/user-attachments/assets/8bf408e0-35df-42f2-90b8-22ae477904d1)
![extension](https://github.com/user-attachments/assets/bb239a65-4334-40e4-957d-547d81d8756e)

La connexion à YGG :
![SNAG-0015](https://github.com/user-attachments/assets/65c70bef-fc81-4c42-b109-794ba00d0888)

Le torrent téléchargé (Y'a pas de honte ? Si? ...) :
![SNAG-0014](https://github.com/user-attachments/assets/5af19739-75ae-4c46-b38e-97a9a244463f)

Erreur :
![erreur](https://github.com/user-attachments/assets/fab10e66-30bf-49d9-852d-d4c0868e165f)

Voilà :)

**Comment by P00nY** [comment]
Salut,

Je ne trouve pas ce torrent sous YGG.
![image](https://github.com/user-attachments/assets/1e337bfb-e59c-4717-8e75-3cdde3a37132).

Je pense que tu as gardé du cache d'autres sites torrent 🤔.

**Comment by LudovicOmarini** [comment]
https://www.ygg.re/torrent/filmvid%C3%A9o/animation/582567-vaiana+-+la+l%C3%A9gende+du+bout+du+monde+2016+multi+vff+2160p+10bit+4klight+hdr+bluray+ac3+5+1+x265-qtz+moana

Il est bien là pourtant, en tapant juste vaiana et en triant par seed

Cela me faire le problème sur tout les torrents ygg

**Comment by LudovicOmarini** [comment]
Pour le coup quand je recupere les torrents depuis mon ordi via le lien : https://127.0.0.1/ygg.php?torrent=www.ygg.re/engine/download_torrent?id=******&cookie=/tmp/yggtorrent.cookie

Et que j'édite le torrent téléchargé avec Notepad il y a dedans :

<!DOCTYPE html>
<html lang="en-US">
   <head>
      <title>Just a moment...</title>
     ...
     <div class="main-wrapper" role="main">
         <div class="main-content">
            <noscript>
               <div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div>
            </noscript>
         </div>
      </div>
     ....

Soit pas du tout la tête d'un torrent normal.

**Comment by P00nY** [comment]
Normal le .cookie et le fichier tampon pour que la connexion s'effectue avec tes identifiants. 
Effectivement, 
Je le trouve juste en tapant 'Vaiana'
![image](https://github.com/user-attachments/assets/846f9132-11fe-4c6e-bb9a-466adf03afd1)
0/ supprimer tes identifiants YGG sur download station 
1/ Supprimer download Station
2/ delete l'enregistrement CURL
3/ reboot ton NAS
4/ réinstalle download Station 
5/ Active la recherche Torrent piratebay 
6/ fais une recherche 
7/ Si la recherche fonctionne, configuration du CURL
8/ ajout du Répo YGG + test co
9/ faire une recherche Avec YGG + Piratebay
10/ si ok décoche piratebay
11/ relance ta recherche

**Comment by LudovicOmarini** [comment]
Salut, j'ai tout suivi à la lettre mais j'ai toujours la même erreur.
J'arrive bien jusqu'a la dernière étape. Mais le torrent télécharger n'est pas valide.

**Comment by Trackerz** [comment]
Actuellement je n'ai pas mon NAS sous la main pour debug mais j'ai déjà eu ce problème au niveau du download.
Essaye de passer ton php en version 7.2 ou 7.3.

**Comment by P00nY** [comment]
Hello @Trackerz, 
Je pense que tu peux close l'issue ^^ pas news bonne news

**Comment by LudovicOmarini** [comment]
Oups, désolé de pas avoir donner de nouvelles, meme, j'ai essayé toute les versions de php et malheuresement toujours le même problème

**Comment by P00nY** [comment]
Hello,
Je vais essayer sur un autre NAS.
Et voir..

**Comment by P00nY** [comment]
J'ai testé sur un autre NAS et ça fonctionne.. 😶

**Comment by Trackerz** [comment]
De mon coté ca fonctionne aussi, donne moi la version de ton DSM + PHP car la je ne comprends pas.

Ajoute moi sur Discord trackerz#1588 qu'on regarde

**Comment by Trackerz** [comment]
Ca venait du fichier ygg.php, étrangement chez lui c'est l'ancienne version qui fonctionne mais impossible de comprendre pourquoi.

On va dire que c'était une exception :)

**Comment by P00nY** [comment]
Bonne nouvelle !
