### ISSUE TITLE
Invalid DLM file created by tar command

### ISSUE THREAD

**Issue by r3c** [Trackerz/Yggtorrent-DLM#3]
Hello and thank you for this plugin!

I'm probably doing something wrong and my issue is likely not related to your code, however I'd appreciate some help to get it working in case you already ran across a similar issue. I tried to build the `yggtorrent.dlm` file using command from README:

`tar zcf yggtorrent.dlm INFO search.php`

However when trying to add `yggtorrent.dlm` as a search engine I get a "search engine plugin is invalid" error ("Le plug-in de moteur de recherche est invalide." as I'm using french version, not sure what's the exact english translation). I tried tar command on a Windows (Cygwin) host, a Linux (Ubuntu 20) one and Synology server itself, but got the same result each time. Generated file looks a valid gzipped tarball file according to `file` utility, and properly creates `INFO` and `search.php` (with their original contents) when running `tar xzf yggtorrent.dlm` on any of the tree hosts mentioned above.

Is there something else I'm missing before the file can be used in DSM?

Thank you for your help!

**Comment by Trackerz** [comment]
Salut au cas ou le fichier `yggtorrent.dlm` est fourni déjà compilé dans la release tu n'est pas obligé de le compiler toi meme !
Sinon je viens de tester de compiler le plugin et de l'ajouter dans Download Station ça fonctionne correctement de mon coté. T'as fait des modifications dans le code ou c'est les fichiers de base?

La commande pour compiler est bien celle ci `tar zcf yggtorrent.dlm INFO search.php` apres une fois compilé peux-tu vérifier que l'archive contient bien 1 seul fichier comme sur le screenshot cidessous et que ce fichier dans l'archive contient lui meme le code du fichier `INFO` et `search.php`. D'apres ce que tu dis ça te génère bien l'archive mais avec 2 fichiers séparés et ce n'est pas bon.
J'avoue que je ne connais pas vraiment linux donc je sais pas trop comment t'aider, j'avais bêtement utilisé la commande qui était dans la documentation de Synology

![screen](https://i.imgur.com/HiI5rHJ.png)

**Comment by r3c** [comment]
Hello, merci pour la réponse ! Je n'ai pas modifié le code et les vérifications que tu proposes sont OK, mais je pense vraiment que c'est un souci de mon côté et que ton plugin n'est pas en cause. Je posais juste la question au cas où, parce que j'ai cherché un moment et pas moyen de savoir d'où ça vient ! Merci pour l'aide dans tous les cas :)
