### ISSUE TITLE
Le compte ou le mot de passe n'est pas valable.

### ISSUE THREAD

**Issue by Tmpulas** [Trackerz/Yggtorrent-DLM#5]
Salut.

J'ai suivi les étapes d'installation, mais quand je veut tester le dlm en mettant le nom d'utilisateur et mot de passe du site, j'ai le message "Le compte ou le mot de passe n'est pas valable.". Or, ces identifiants marchent bel et bien sur le site !

**Comment by antoine49380** [comment]
Bonjour,
Même difficulté de mon coté.
php et dlm chargés, Curl activé, services WebStation et DownloadStation redémarrés, le pb persiste.
Compte ok sur le site Ygg

**Comment by Trackerz** [comment]
Salut effectivement ca ne fonctionne plus à cause de la protection Cloudflare qui est de nouveau présente sur le site depuis 1 semaine
C'est trop compliqué à contourner étant donné la limitation de Synology dans les modules et ca ne tient de toute façon pas dans le temps...
Il faut attendre un peu et peut être qu'avec de la chance Cloudflare va être de nouveau retiré mais pour le moment je ne peux pas faire grand chose désolé :'(

**Comment by antoine49380** [comment]
Salut, merci pour cette explication et le temps passé sur le développement de ce module ! Pressé que la protection saute ! ;)

**Comment by Trackerz** [comment]
Cloudflare semble avoir été retiré ca fonctionne de nouveau 😎👍

**Comment by antoine49380** [comment]
Bonjour, je confirme ! 😉
Recherche et ajout ok.
Juste un pb de cookies mais je vais regarder plutôt du côté du serveur web.
Bon week-end !

**Comment by Trackerz** [comment]
Pour supprimer le cookie et repartir à zero il faut faire ceci en ssh avec un compte administrateur :

1 : ssh ip -p port -l identifiant (exemple ssh 192.168.0.1 -p 22 -l admin)
2 : sudo -i puis taper le mot de passe du compte utilisateur une nouvelle fois
3 : cd /tmp
4 : rm *ygg*

**Comment by Tmpulas** [comment]
Thanks for the follow up. Work well for me now !

**Comment by Tmpulas** [comment]
Merci pour le suivi. Ça marche bien de mon côté !
