### ISSUE TITLE
message d'erreur "Le compte ou le mot de passe n'est pas valable"

### ISSUE THREAD

**Issue by lottox17** [Trackerz/Yggtorrent-DLM#6]
Bonjour,

je viens d'installer le DLM sur mon synology en ayant suivi chaque étapes.

J'ai le message d'erreur suivant qui s'affiche au moment de la vérification du compte ygg : "Le compte ou le mot de passe n'est pas valable"

Pourtant mon compte est fonctionnel, est-ce que cela vient de moi ?

Merci

**Comment by ggenot** [comment]
Bonjour, j'ai le même soucis je pense que ça vient de Cloudflare, 

Je suis en train de DEBUG de mon coté mais ce que je vois c'est que la fonction getSubDomain (L373) reçoit la page cloudflare et est donc incapable de parser l'URL. Ce qui provoque un crash du script php et on reçoit un erreur générique. 

Si je trouve une solution je ferai une PR 

Cheers

**Comment by MatthieuPecheur** [comment]
Bonjour, j'ai le même problème, merci à toi ggenot pour ta recherche de résolution

**Comment by ggenot** [comment]
Bon, j'ai regardé un peu et bypass cloudflare c'est du bricolage, évidement puisque c'est fait pour éviter les attaques via BOT. :/ 

Concrètement il faudrait émuler un vrai navigateur internet et espérer ne pas avoir de captcha. Ou demander au admins de ygg de fournir un API mais je pense pas qu'ils soient intéressés. Bref c'est mort :(

**Comment by MatthieuPecheur** [comment]
Je n'y connais rien en PHP, mais n'est-il pas possible d'utiliser ce code pour bypasser cloundflare  : [https://github.com/yani/PHP-v8js-CloudFlare-bypass] ?

**Comment by Trackerz** [comment]
Non il n'est pas possible d'utiliser cette librairie elle n'est plus à jour depuis 4ans malheureusement et les scripts de bypass en php sont tres rapidement contournés...il y a des solutions mais c'est trop compliqué a mettre en plus juste pour ca et personne va vouloir s'embêter à installer nodejs ou python.

Voila donc pour le moment j'ai abandonné mais le script fonctionne quand Cloudflare n'est plus actif sur le site ce qui arrive de temps en temps

**Comment by Trackerz** [comment]
Le plugin fonctionne de nouveau avec la version 1.3.1 sur DSM6 et 7
