### ISSUE TITLE
Echec de la recherche

### ISSUE THREAD

**Issue by DJembeCLEMfola** [Trackerz/Yggtorrent-DLM#7]
Bonjour,

Après avoir suivi les instructions :

![2021-07-21 19_26_41-SRV-MEZKAL - Synology DiskStation](https://user-images.githubusercontent.com/87776908/126533831-c5c73d3e-919d-42cb-a585-20a3ea1e0e80.png)
Avec CURL activé

![2021-07-21 19_26_18-SRV-MEZKAL - Synology DiskStation](https://user-images.githubusercontent.com/87776908/126533851-b2361803-a9fc-4978-b2d1-9465a5c9e094.png)
![2021-07-21 19_25_35-SRV-MEZKAL - Synology DiskStation](https://user-images.githubusercontent.com/87776908/126533221-f2d0d0f0-b59d-4f92-80f3-27f5a8715b5f.png)

Malgré tout, la recherche indique
![2021-07-21 19_28_33-SRV-MEZKAL - Synology DiskStation](https://user-images.githubusercontent.com/87776908/126533196-4cf94750-956d-4d3b-b63f-2727eaab1f67.png)

**Comment by Cadkey** [comment]
Bonjour,
Même problème pour moi, installation strictement identique sur un 920+ DSM 6.2

**Comment by jmb49** [comment]
Bonjour, même situation chez moi, pourtant DNS Orange changés côté Synology (DSM 6.2.4-25556, ensemble des packages à jour). A moins que ce ne soit PHP en v7.4 qui ne colle pas pour ce moteur ? Très bonne soirée & WE ;))

**Comment by DJembeCLEMfola** [comment]
> 
> 
> Bonjour, même situation chez moi, pourtant DNS Orange changés côté Synology (DSM 6.2.4-25556, ensemble des packages à jour). A moins que ce ne soit PHP en v7.4 qui ne colle pas pour ce moteur ? Très bonne soirée & WE ;))

J'ai essayé avec les autres versions de PHP et j'obtiens le même résultat.

**Comment by Trackerz** [comment]
Salut, je viens de push une mise à jour pour régler un problème avec la récupération de la date qui plantait l'affichage des torrents ca devrait être bon maintenant par contre il faudrait faire ceci :

- Supprimer le plugin YGGTorrent dans DLStation
- Supprimer DLStation
- Réinstaller DLStation
- Réinstaller le plugin

**Comment by DJembeCLEMfola** [comment]
Salut,

J'ai dl la maj et j'ai appliqué les actions au dessus.
J'ai même supprimé la bdd yggtorrent à la désinstallation.

Pas de changement de mon coté toujours échec de la recherche alors qu'il m'indique que les identifiants sont bons.
J'ai essayé avec PHP 7.4 & 5.6 --> idem

**Comment by ylamarche** [comment]
erreur lors de la connexion impossible de rechercher pourtant tout fait se qui est écrit ?

**Comment by Trackerz** [comment]
C'est un peu compliqué de débugger à l'aveugle car je n'ai plus de DSM 6 à dispo mais j'ai identifié un problème je pense que cette version doit fonctionner 

[https://github.com/Trackerz/Yggtorrent-DLM/blob/beta/yggtorrent.dsm6.dlm](url)

Je suis dispo sur discord si ca ne marche pas pour regarder ce qu'il se passe -> Trackerz1588

**Comment by ylamarche** [comment]
Sa ne fonctionne pas plus,

**Comment by DJembeCLEMfola** [comment]
Bizarrement, j'ai fais la mise à jour du DSM en version 7 et ça s'est mis à fonctionné.

**Comment by Trackerz** [comment]
@DJembeCLEMfola Oui c'est un problème qui apparait uniquement sur DSM 6 il a comportement étrange je ne comprends pas pourquoi

@ylamarche J'ai pu le faire fonctionner sur un DSM 6 virtuel de mon coté, tu as discord?

Tu peux essayer de ca dans un premier temps en te connectant en SSH avec un compte admin sur le NAS : 

1 : ssh ip -p port -l identifiant (exemple ssh 192.168.0.1 -p 22 -l admin)
2 : sudo -i puis taper le mot de passe du compte utilisateur une nouvelle fois
3 : cd /tmp
4 : rm * ygg *

Puis : 

5 : Supprimer le plugin YGGTorrent dans DLStation
6 : Supprimer DLStation et cocher la case supprimer la base de donnée
7 : Réinstaller DLStation
8 : Réinstaller le plugin

**Comment by jmb49** [comment]
Après MàJ DSM de 6.x à 7.x, fonctionnement immédiatement OK sans aucune manip de désintallation / réinstallation. Merci :)

**Comment by ylamarche** [comment]
@Trackerz
Sa ne fonctionne pas, je t'ajoute sur discord 
pour info j'utilise Xpenology DSM 6.1 si sa peux t'aider

**Comment by Trackerz** [comment]
Problème résolu avec l'utilisation de la version 1.3.3
