### ISSUE TITLE
Download action not working whent selecting search result

### ISSUE THREAD

**Issue by pbartolo26** [Trackerz/Yggtorrent-DLM#8]
When clicking on the search result, the download fails. 

yygtorrent.cookie is added to the download list with the following statut: "Lien incorrect" 

The following URL seems to be inside the file: 
https://127.0.0.1/ygg.php?torrent=www3.yggtorrent.nz/engine/download_torrent?id=477568&cookie=/tmp/yggtorrent.cookie

Maybe the 127.0.0.1 URL us not natively supported in the webstation ? 

Thanks in advance for your help. 

Patrick

**Comment by pbartolo26** [comment]
slt ! ça sera plus facile en français :-D 

Oui j'ai fais tout ce que tu as décris dans ton tuto. Je suspecte effectivement un soucis du côté de web station qui ne reconnais pas l'URL, mais je ne sais pas comment le vérifier. 

Peut-être que le 127.0.0.1 n'est pas reconnu pas défaut et qu'il faudrait utiliser plutôt localhost non ? 

merci vraiment pour ton aide ! ça serai vraiment cool de faire marcher ton hook !!!

**Comment by Trackerz** [comment]
Quand tu test les identifiants tu as bien le message qui indique que la connexion est réussie?

Je te confirme que le 127.0.0.1 c'est bon le problème ne vient pas de la.

Ajoute moi sur discord si tu as qu'on regarde ca plus simplement Trackerz#1588

**Comment by pbartolo26** [comment]
c'est bon j'ai trouvé. Dans la config du serveur principal HTTP nginx de webstation, il faut choisir dedault profile 'php7' dans le menu déroulant pour PHP. 

Après le requêtes vont bien jusqu'à ton script !

**Comment by Trackerz** [comment]
Ca marche je pensais que tu l'avais fait mais c'est vrai que c'est pas ultra clair je vais préciser cette étape 👍

**Comment by pbartolo26** [comment]
Bon ben ça redéconne ! Je ne comprend pas ce qui a bien pu changer :/ 

![image](https://user-images.githubusercontent.com/89660523/145043316-141c975c-1a7c-4b56-9b52-f70122aa31c9.png)

**Comment by jsncrdnl** [comment]
Bonjour (et un grand merci pour ce développement) 😁 

J'ai le même souci que @pbartolo26 

![image](https://user-images.githubusercontent.com/2870621/146776304-17544206-debb-4fbb-9735-ab86d4bafc8a.png)

Est-ce que ça n'aurait pas à voir avec le fait que les serveur local est appelé avec HTTPS plutot que HTTP (le certificat n'étant alors pas reconnu) ?  
Est-il possible de remplacer le HTTPS en HTTP ou de renseigner l'url publique du web serveur pour qu'il utilise le certificat (du domaine synology) ?

Merci d'avance

**Comment by jsncrdnl** [comment]
Just tried to rebuild the DLM file changing the HTTPS to HTTP but did not make a change  
Still getting the same error `fichier torrent non valide`

**Comment by Trackerz** [comment]
Hi the issue is because cloudflare came back to yggtorrent and i'm not able to bypass it with only php so for the moment there is no solution sorry

**Comment by mtcbwc** [comment]
bonjour,hello,
c'est toujours d'actualité le cloudfare sur ygg?
cdlt.

**Comment by mtcbwc** [comment]
@Trackerz hélas je ne télécharge rien sans VPN. 
c'est dommage qu'on ne puisse pas en profiter avec un vpn.
il n'y aucun autre moyen ?

**Comment by tolask** [comment]
Salut,
Exactement le meme probleme ici... Je pense avoir tout installé correctement. 
Le plugin est configuré, le Test est OK.
La recherche fonctionne, j'ai bien les resultats dans la liste.
Par contre quand je double click sur un element de la recherche, une tache de download se cree mais elle est intitulee "yggtorrent.cookie" et ne fonctionne bien évidemment pas...

PS: pas de VPN
